"""empty message

Revision ID: 045cf4138df6
Revises: 
Create Date: 2018-02-27 23:37:01.311908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045cf4138df6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('body')
    )
    op.create_table('tag_post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['post_tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.add_column('posts', sa.Column('brief', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'brief')
    op.drop_table('tag_post')
    op.drop_table('post_tags')
    # ### end Alembic commands ###
