"""empty message

Revision ID: 2669e399943e
Revises: 5819ae39c142
Create Date: 2017-10-13 16:22:26.326581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2669e399943e'
down_revision = '5819ae39c142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='roles')
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('name', 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
